package proxy

const (
	REQUEST_LOGGER_EMMIT = "REQUEST_LOGGER_EMMIT"
	DEFAULT_VERSION = "1"
	GOWAY_PRODUCT= "GOWAY_PRODUCT"
	GOWAY_CLIENT= "GOWAY_CLIENT"
	GOWAY_VERSION = "GOWAY_VERSION"
	API_ROUTE_NOT_FOUND = "API_ROUTE_NOT_FOUND"
	ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND"
	AUTHENTICATION_HANDLER = "AUTHENTICATION"
	CUSTOM_HANDLER = "HANDLER_ERROR"
	API_KEY_NOT_FOUND = "API_KEY_NOT_FOUND"
)
